2023-11-27 20:58:00,732:INFO:Training data created successfully.
2023-11-27 20:58:00,865:WARNING:From C:\Users\zhy011\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2023-11-27 20:58:01,938:WARNING:From C:\Users\zhy011\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

2023-11-27 20:58:03,437:ERROR:Error in LSTM_model : Failed to convert a NumPy array to a Tensor (Unsupported object type float).
2023-11-27 20:58:03,437:ERROR:Error in main : Failed to convert a NumPy array to a Tensor (Unsupported object type float).
2023-11-27 21:03:03,750:INFO:Training data created successfully.
2023-11-27 21:03:03,884:WARNING:From C:\Users\zhy011\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2023-11-27 21:03:03,916:ERROR:Error in LSTM_model : tuple index out of range
2023-11-27 21:03:03,916:ERROR:Error in main : tuple index out of range
2023-11-27 21:07:35,621:INFO:Training data created successfully.
2023-11-27 21:07:35,796:WARNING:From C:\Users\zhy011\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2023-11-27 21:07:35,831:ERROR:Error in LSTM_model : tuple index out of range
2023-11-27 21:07:35,832:ERROR:Error in main : tuple index out of range
2023-11-27 21:12:44,357:ERROR:Error in create_training_data: could not convert string to float: '2019/1/1 0:00'
2023-11-27 21:12:44,357:ERROR:Error in main : could not convert string to float: '2019/1/1 0:00'
2023-11-27 21:19:20,750:INFO:Training data created successfully.
2023-11-27 21:19:20,873:WARNING:From C:\Users\zhy011\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2023-11-27 21:19:21,957:WARNING:From C:\Users\zhy011\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

2023-11-27 21:19:23,557:WARNING:From C:\Users\zhy011\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

2023-12-04 20:36:03,797:INFO:Training data created successfully.
2023-12-05 22:40:52,485:INFO:Training data created successfully.
2023-12-05 22:46:12,119:INFO:Training data created successfully.
2023-12-05 22:49:51,813:INFO:Training data created successfully.
2023-12-06 05:29:12,224:INFO:Training completed. Final loss: nan, Final validation loss: nan
2023-12-06 05:29:12,624:INFO:Last timestamp saved successfully in D:/MarketMasterAI/bin/Last_timestamp.json
2023-12-06 05:29:12,999:INFO:Training data created successfully.
2023-12-06 07:36:33,701:INFO:Training completed. Final loss: nan, Final validation loss: nan
2023-12-06 07:36:33,840:INFO:Last timestamp saved successfully in D:/MarketMasterAI/bin/Last_timestamp.json
2023-12-06 07:36:34,028:INFO:Training data created successfully.
2023-12-06 08:37:42,908:INFO:Training completed. Final loss: nan, Final validation loss: nan
2023-12-06 08:37:42,980:INFO:Last timestamp saved successfully in D:/MarketMasterAI/bin/Last_timestamp.json
2023-12-06 08:37:43,076:INFO:Training data created successfully.
2023-12-06 09:07:59,884:INFO:Training completed. Final loss: nan, Final validation loss: nan
2023-12-06 09:07:59,925:INFO:Last timestamp saved successfully in D:/MarketMasterAI/bin/Last_timestamp.json
2023-12-06 09:07:59,959:INFO:Training data created successfully.
2023-12-06 09:15:33,486:INFO:Training completed. Final loss: nan, Final validation loss: nan
2023-12-06 09:15:33,496:INFO:Last timestamp saved successfully in D:/MarketMasterAI/bin/Last_timestamp.json
2023-12-06 09:15:33,520:INFO:Training data created successfully.
2023-12-06 09:16:53,765:INFO:Training completed. Final loss: nan, Final validation loss: nan
2023-12-06 09:16:53,769:INFO:Last timestamp saved successfully in D:/MarketMasterAI/bin/Last_timestamp.json
2023-12-06 09:16:53,826:INFO:Model saved successfully at D://MarketMasterAI//bin//LSTM_5T.h5
2023-12-06 09:16:53,840:INFO:Model saved successfully at D://MarketMasterAI//bin//LSTM_15T.h5
2023-12-06 09:16:53,853:INFO:Model saved successfully at D://MarketMasterAI//bin//LSTM_30T.h5
2023-12-06 09:16:53,866:INFO:Model saved successfully at D://MarketMasterAI//bin//LSTM_1H.h5
2023-12-06 09:16:53,880:INFO:Model saved successfully at D://MarketMasterAI//bin//LSTM_4H.h5
2023-12-06 09:16:53,893:INFO:Model saved successfully at D://MarketMasterAI//bin//LSTM_1D.h5
2023-12-06 09:16:53,893:INFO:Main function executed successfully.
2023-12-06 17:41:17,754:INFO:Training data created successfully.
2023-12-06 17:41:18,272:INFO:loading LSTM model successfully.
2023-12-06 17:41:18,273:ERROR:Error in retrain_model : Training data contains 0 samples, which is not sufficient to split it into a validation and training set as specified by `validation_split=0.2`. Either provide more data, or a different value for the `validation_split` argument.
2023-12-06 17:41:18,273:ERROR:Error in main: Training data contains 0 samples, which is not sufficient to split it into a validation and training set as specified by `validation_split=0.2`. Either provide more data, or a different value for the `validation_split` argument.
2023-12-06 17:41:50,901:INFO:Training data created successfully.
2023-12-06 17:41:51,376:INFO:loading LSTM model successfully.
2023-12-06 17:41:51,376:ERROR:Error in retrain_model : Training data contains 0 samples, which is not sufficient to split it into a validation and training set as specified by `validation_split=0.2`. Either provide more data, or a different value for the `validation_split` argument.
2023-12-06 17:41:51,377:ERROR:Error in main: Training data contains 0 samples, which is not sufficient to split it into a validation and training set as specified by `validation_split=0.2`. Either provide more data, or a different value for the `validation_split` argument.
2023-12-06 17:44:03,190:INFO:Training data created successfully.
2023-12-06 17:45:23,494:INFO:Training data created successfully.
2023-12-06 17:46:45,593:INFO:Training data created successfully.
2023-12-06 17:50:12,346:INFO:Training data created successfully.
2023-12-06 17:55:08,520:INFO:Training data created successfully.
2023-12-06 19:57:39,461:INFO:Training data created successfully.
2023-12-06 19:57:40,925:ERROR:Error in LSTM_model : in user code:

    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1080, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 60, 5), found shape=(None, 60, 4)

2023-12-06 19:57:40,926:ERROR:Error in main: in user code:

    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1080, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 60, 5), found shape=(None, 60, 4)

2023-12-06 20:22:08,988:INFO:Training data created successfully.
2023-12-06 20:44:15,069:INFO:Training data created successfully.
2023-12-06 20:48:00,518:INFO:Training data created successfully.
2023-12-06 20:48:01,660:ERROR:Error in LSTM_model : in user code:

    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1080, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 60, 5), found shape=(None, 60, 4)

2023-12-06 20:48:01,661:ERROR:Error in main: in user code:

    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1080, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\nrnye\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 60, 5), found shape=(None, 60, 4)

2023-12-06 20:48:33,253:INFO:Training data created successfully.
2023-12-06 20:49:34,123:INFO:Training data created successfully.
2023-12-06 20:50:06,713:INFO:Training data created successfully.
2023-12-06 20:51:04,482:INFO:Training data created successfully.
